### ISSUE TITLE
Undeclared dependency on @daybrush/jsdoc

### ISSUE THREAD

**Issue by preaction** [naver/jsdoc-to-mdx#15]
After installing `jsdoc-to-mdx` with `npm i -D jsdoc-to-mdx`, running `jsdoc-to-mdx -c config.json` results in the following error:

```

node:internal/modules/cjs/loader:1026
  const err = new Error(message);
              ^

Error: Cannot find module '@daybrush/jsdoc/jsdoc.js'
Require stack:
- /Users/doug/games/bitwise/docs/node_modules/jsdoc-to-mdx/bin/generate.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at /Users/doug/games/bitwise/docs/node_modules/jsdoc-to-mdx/bin/generate.js:514:73
    at Generator.next (<anonymous>)                                                                                                                               at /Users/doug/games/bitwise/docs/node_modules/jsdoc-to-mdx/bin/generate.js:58:71                                                                             at new Promise (<anonymous>)
    at __awaiter (/Users/doug/games/bitwise/docs/node_modules/jsdoc-to-mdx/bin/generate.js:54:12)
    at tmp__default.default.withDir.unsafeCleanup (/Users/doug/games/bitwise/docs/node_modules/jsdoc-to-mdx/bin/generate.js:511:46)
    at Object.withDir (/Users/doug/games/bitwise/docs/node_modules/tmp-promise/index.js:37:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/doug/games/bitwise/docs/node_modules/jsdoc-to-mdx/bin/generate.js'
  ]
}
```

Installing `@daybrush/jsdoc` with `npm i -D @daybrush/jsdoc` fixes the problem.

**Comment by WoodNeck** [comment]
Hello @preaction! Thanks for reporting the issue.
I found out that there's a problem with our dependencies, I'll fix that in the next version :)
